// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * "Wizz Us Team" <{MAIL_USER}>"
	 * @param {unknown} MAIL_USER
	 */
	SET_CONFIRMATION_MAIL_FROM: RequiredParams<'MAIL_USER'>
	/**
	 * Please confirm your account
	 */
	SET_CONFIRMATION_MAIL_SUBJECT: string
	/**
	 * Hi, 
		Thank you for subscribing to Wizz-Us. 
		Please confirm your email by copying and pasting the following link in your browser :
		{BACK_URL}/signup-confirmation/{confirmationCode}
	 * @param {unknown} BACK_URL
	 * @param {unknown} confirmationCode
	 */
	SET_CONFIRMATION_MAIL_TEXT: RequiredParams<'BACK_URL' | 'confirmationCode'>
	/**
	 * <b>
			Hi,</br>
			Thank you for subscribing to Wizz-Us.</br>
			Please confirm your email by clicking on the following link :</br>
			<a href='{BACK_URL}/signup-confirmation/{confirmationCode}'> Click here</a>
		</b>
	 * @param {unknown} BACK_URL
	 * @param {unknown} confirmationCode
	 */
	SET_CONFIRMATION_MAIL_HTML: RequiredParams<'BACK_URL' | 'confirmationCode'>
}

export type TranslationFunctions = {
	/**
	 * "Wizz Us Team" <{MAIL_USER}>"
	 */
	SET_CONFIRMATION_MAIL_FROM: (arg: { MAIL_USER: unknown }) => LocalizedString
	/**
	 * Please confirm your account
	 */
	SET_CONFIRMATION_MAIL_SUBJECT: () => LocalizedString
	/**
	 * Hi, 
		Thank you for subscribing to Wizz-Us. 
		Please confirm your email by copying and pasting the following link in your browser :
		{BACK_URL}/signup-confirmation/{confirmationCode}
	 */
	SET_CONFIRMATION_MAIL_TEXT: (arg: { BACK_URL: unknown, confirmationCode: unknown }) => LocalizedString
	/**
	 * <b>
			Hi,</br>
			Thank you for subscribing to Wizz-Us.</br>
			Please confirm your email by clicking on the following link :</br>
			<a href='{BACK_URL}/signup-confirmation/{confirmationCode}'> Click here</a>
		</b>
	 */
	SET_CONFIRMATION_MAIL_HTML: (arg: { BACK_URL: unknown, confirmationCode: unknown }) => LocalizedString
}

export type Formatters = {}
